version: '3.9'
services:
  python:
    image: raulscontainerreg.azurecr.io/best-city-python:latest
    container_name: python-scraper
    build:
      context: ./
      dockerfile: ./containers/python/Dockerfile
    working_dir: /opt/app
    tty: true
