version: '3.9'
services:
  python:
    container_name: python_scraper
    build: ./containers/python
    volumes:
      - .:/opt/application
    working_dir: /opt/application
    tty: true
    command: sh -c "python main.py"
